{
    "version": "v1",
    "blocklist": [],
    "data": [
        {
            "id": "2d_cutout_people",
            "name": "2D Cutout People",
            "tagline": "Do 2D Cutout People with genAI",
            "version": "1.0",
            "type": "add-on",
            "archive_size": null,
            "archive_hash": null,
            "archive_url": null,
            "blender_version_min": "3.0.0",
            "maintainer": "tintwotin",
            "tags": ["3D View"],
            "license": ["SPDX:GPL-3.0-or-later"],
            "website": null,
            "schema_version": "1.0.0"
        }
    ]
}
